import { db } from "./db";
import { products } from "@shared/schema";

const PRICES = [200, 210, 220, 230, 240, 250];
const DISCOUNT_PRICES = [95, 100, 110];

function randomPrice() {
  return PRICES[Math.floor(Math.random() * PRICES.length)];
}

function discountTier(name: string): number {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = ((hash << 5) - hash) + name.charCodeAt(i);
    hash |= 0;
  }
  return DISCOUNT_PRICES[Math.abs(hash) % DISCOUNT_PRICES.length];
}

const seedProducts = [
  {
    name: "Ford Mustang Shelby GT500",
    description: "A bold tribute to the iconic 1967 Shelby GT500CR 545. Ultra-light carbon fiber cladding meets raw American muscle in this stunning matte black poster. Perfect for car enthusiasts and collectors. Printed on premium 250gsm matte paper.",
    price: randomPrice(),
    discountPrice: discountTier("Ford Mustang Shelby GT500"),
    image: "/images/poster-cars-1.jpeg",
    category: "Cars",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Ferrari F1 V12 Racer",
    description: "Feel the roar of the Ferrari V12 engine with this top-down view of the iconic red F1 car. Featuring detailed specs and the legendary prancing horse badge. A must-have for Formula 1 fans. Museum-quality archival print.",
    price: randomPrice(),
    discountPrice: discountTier("Ferrari F1 V12 Racer"),
    image: "/images/poster-cars-2.jpeg",
    category: "Cars",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Land Rover Defender 110",
    description: "The rugged elegance of the Defender 110 captured in stunning detail. 5.0L V12 power meets classic British engineering in this premium matte black poster. Built for adventure, designed for your wall.",
    price: randomPrice(),
    discountPrice: discountTier("Land Rover Defender 110"),
    image: "/images/poster-cars-3.jpeg",
    category: "Cars",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Mercedes AMG G63 Brabus",
    description: "The ultimate statement of luxury performance. The Brabus-tuned AMG G63 with 900HP dominates this poster in striking grey. Detailed specs and German engineering excellence on display. Premium satin finish.",
    price: randomPrice(),
    discountPrice: discountTier("Mercedes AMG G63 Brabus"),
    image: "/images/poster-cars-4.jpeg",
    category: "Cars",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Monkey D. Luffy Wanted Poster",
    description: "The legendary Straw Hat pirate's bounty poster brought to life. Monkey D. Luffy with his iconic grin and a bounty of 500,000,000 berries. A timeless One Piece collectible for every anime fan. Archival-quality print.",
    price: randomPrice(),
    discountPrice: discountTier("Monkey D. Luffy Wanted Poster"),
    image: "/images/poster-anime-1.jpeg",
    category: "Anime",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Spider-Man Web Slinger",
    description: "Your friendly neighborhood Spider-Man in a stunning Marvel Studios collector edition poster. Peter Parker's dual identity captured in cinematic detail with the iconic NYC skyline. Premium satin finish with vivid, fade-resistant inks.",
    price: randomPrice(),
    discountPrice: discountTier("Spider-Man Web Slinger"),
    image: "/images/poster-anime-2.jpeg",
    category: "Anime",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Gojo Satoru Domain Expansion",
    description: "The strongest sorcerer of Jujutsu High in his signature pose. This stunning manga collage captures Gojo Satoru's most iconic moments from Jujutsu Kaisen. Bold black and white art with incredible detail. Gallery-grade print.",
    price: randomPrice(),
    discountPrice: discountTier("Gojo Satoru Domain Expansion"),
    image: "/images/poster-anime-3.jpeg",
    category: "Anime",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Itachi Uchiha Akatsuki Legend",
    description: "The legendary Uchiha prodigy in his Akatsuki cloak, Sharingan blazing. This striking Naruto poster captures Itachi's enigmatic presence with manga panel art background. A masterpiece for every shinobi fan.",
    price: randomPrice(),
    discountPrice: discountTier("Itachi Uchiha Akatsuki Legend"),
    image: "/images/poster-anime-4.jpeg",
    category: "Anime",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Starry Night Van Gogh Art",
    description: "Vincent van Gogh's masterpiece reimagined as a premium wall poster. The swirling night sky reflected over calm waters creates a mesmerizing atmosphere. A timeless piece of art for any space. Printed on heavyweight fine art paper.",
    price: randomPrice(),
    discountPrice: discountTier("Starry Night Van Gogh Art"),
    image: "/images/poster-anime-5.jpeg",
    category: "Anime",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Virat Kohli Action Frame",
    description: "King Kohli in his element — a powerful collage of the greatest modern batsman's iconic moments. From match-winning celebrations to record-breaking innings. 'If there is 1% chance, that chance is good enough.' Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Virat Kohli Action Frame"),
    image: "/images/poster-cricket-1.jpeg",
    category: "Cricket",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "MS Dhoni Captain Cool",
    description: "Captain Cool in his legendary helicopter shot pose. This dynamic poster captures Dhoni's most iconic cricketing moments in a stunning blue and black collage. A tribute to India's greatest captain. Archival-quality print.",
    price: randomPrice(),
    discountPrice: discountTier("MS Dhoni Captain Cool"),
    image: "/images/poster-cricket-2.jpeg",
    category: "Cricket",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Cristiano Ronaldo CR7 Legend",
    description: "The GOAT in his classic Manchester United celebration. This bold red poster captures Ronaldo's raw emotion and power on the pitch. Number 7 in all his glory. Vivid, fade-resistant inks on premium matte paper.",
    price: randomPrice(),
    discountPrice: discountTier("Cristiano Ronaldo CR7 Legend"),
    image: "/images/poster-football-1.jpeg",
    category: "Football",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Red Bull RB16B F1 Racer",
    description: "The championship-winning Red Bull Racing RB16B captured in stunning top-down detail. Featuring the iconic Red Bull livery, V12 engine specs and Honda power unit. A must-have for every F1 enthusiast. Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Red Bull RB16B F1 Racer"),
    image: "/images/poster-cars-5.jpeg",
    category: "Cars",
    featured: false,
    orientation: "landscape",
    isNew: false,
  },
  {
    name: "Mercedes AMG Petronas F1",
    description: "The legendary Mercedes W12 in its silver and teal livery. Lewis Hamilton's number 44 car with full engine specs and championship pedigree. Founded in 1926, a legacy of winning. Museum-quality archival print.",
    price: randomPrice(),
    discountPrice: discountTier("Mercedes AMG Petronas F1"),
    image: "/images/poster-cars-6.jpeg",
    category: "Cars",
    featured: false,
    orientation: "landscape",
    isNew: false,
  },
  {
    name: "McLaren MCL35M Papaya",
    description: "The iconic McLaren in its signature papaya orange livery. Daniel Ricciardo's number 3 car with detailed engine specs and racing heritage since 1963. Bold design for bold fans. Premium satin finish.",
    price: randomPrice(),
    discountPrice: discountTier("McLaren MCL35M Papaya"),
    image: "/images/poster-cars-7.jpeg",
    category: "Cars",
    featured: false,
    orientation: "landscape",
    isNew: false,
  },
  {
    name: "Lewis Hamilton F1 Portrait",
    description: "Sir Lewis Hamilton captured in a striking portrait with the Ferrari prancing horse. Seven-time world champion, racing legend, and cultural icon. Bold red and monochrome design on premium matte paper.",
    price: randomPrice(),
    discountPrice: discountTier("Lewis Hamilton F1 Portrait"),
    image: "/images/poster-cars-8.jpeg",
    category: "Cars",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Mike Tyson Boxing Legend",
    description: "Iron Mike Tyson in all his glory. The Noble Art of Boxing captured in a striking red and black collage. Championship belts, knockout moments, and raw power on display. Gallery-grade heavyweight print.",
    price: randomPrice(),
    discountPrice: discountTier("Mike Tyson Boxing Legend"),
    image: "/images/poster-others-1.jpeg",
    category: "Others",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Gervonta 'Tank' Davis",
    description: "The explosive Gervonta Davis in a dramatic black and white collage. Tank's devastating power and lightning speed captured in stunning detail. Red accent artwork on premium matte paper.",
    price: randomPrice(),
    discountPrice: discountTier("Gervonta 'Tank' Davis"),
    image: "/images/poster-others-2.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Muhammad Ali Greatest",
    description: "Float like a butterfly, sting like a bee. The Greatest of All Time standing over his fallen opponent in this iconic illustrated poster. Red and cream color palette. A timeless tribute to the legend. Archival-quality print.",
    price: randomPrice(),
    discountPrice: discountTier("Muhammad Ali Greatest"),
    image: "/images/poster-others-3.jpeg",
    category: "Others",
    featured: true,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Batman Dark Knight",
    description: "I am the shadow they fear. The Dark Knight in a moody, rain-soaked portrait with the iconic bat symbol. Not born a hero, feared by criminals. Vintage grunge aesthetic on premium heavyweight paper.",
    price: randomPrice(),
    discountPrice: discountTier("Batman Dark Knight"),
    image: "/images/poster-others-4.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Avengers Assemble",
    description: "Earth's mightiest heroes united. Captain America, Iron Man, Thor, Hulk, Black Widow, Hawkeye, and Vision in an epic team-up poster. Cinematic detail with vivid, fade-resistant inks on premium satin paper.",
    price: randomPrice(),
    discountPrice: discountTier("Avengers Assemble"),
    image: "/images/poster-others-5.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Captain America Endgame",
    description: "The moment Steve Rogers proved himself worthy. Captain America wielding Mjolnir with his vibranium shield in this stunning close-up portrait. A tribute to the First Avenger. Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Captain America Endgame"),
    image: "/images/poster-others-6.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Deadpool Comic Collage",
    description: "The Merc with a Mouth giving a thumbs up against a classic Marvel comic panel backdrop. Deadpool in all his fourth-wall-breaking glory. Vibrant reds and retro comic art style. Premium satin print.",
    price: randomPrice(),
    discountPrice: discountTier("Deadpool Comic Collage"),
    image: "/images/poster-others-7.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Iron Man Tony Stark",
    description: "Tony Stark, genius billionaire philanthropist. This stunning sepia-toned poster captures the man behind the Iron Man suit in cinematic detail. From weapons manufacturer to selfless hero. Gallery-grade print.",
    price: randomPrice(),
    discountPrice: discountTier("Iron Man Tony Stark"),
    image: "/images/poster-others-8.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Seedhe Maut Collage Art",
    description: "Indian hip-hop duo Seedhe Maut in an eclectic collage poster. From underground rap to sold-out concerts, their journey captured in vibrant mixed-media art. A must-have for desi hip-hop fans. Premium matte paper.",
    price: randomPrice(),
    discountPrice: discountTier("Seedhe Maut Collage Art"),
    image: "/images/poster-others-9.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Seedhe Maut Live Concert",
    description: "Seedhe Maut performing live in this powerful monochrome concert poster. The energy of Indian hip-hop captured in bold typography and grainy photography. Limited edition aesthetic print on heavyweight paper.",
    price: randomPrice(),
    discountPrice: discountTier("Seedhe Maut Live Concert"),
    image: "/images/poster-others-10.jpeg",
    category: "Others",
    featured: false,
    orientation: "portrait",
    isNew: false,
  },
  {
    name: "Cyberpunk Neon Rider",
    description: "A futuristic motorcycle tearing through neon-lit city streets at night. Glowing red wheels and light trails create an electrifying cyberpunk atmosphere. Perfect for sci-fi and bike enthusiasts. Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Cyberpunk Neon Rider"),
    image: "/images/poster-others-11.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Tanjiro Kamado Demon Slayer",
    description: "Tanjiro Kamado in the rain, determination blazing in his eyes. This stunning Demon Slayer poster captures the Water Breathing swordsman in vivid teal and red tones. A must-have for every anime fan. Gallery-grade print.",
    price: randomPrice(),
    discountPrice: discountTier("Tanjiro Kamado Demon Slayer"),
    image: "/images/poster-anime-6.jpeg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
  {
    name: "Spider-Man Above The City",
    description: "Spider-Man perched high above a sprawling metropolis in this breathtaking aerial perspective. The city lights shimmer below as the web-slinger surveys his domain. Cinematic detail on premium satin paper.",
    price: randomPrice(),
    discountPrice: discountTier("Spider-Man Above The City"),
    image: "/images/poster-anime-7.jpeg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Naruto Sage Mode Eyes",
    description: "The legendary Naruto Uzumaki in an intense close-up, his sage mode eyes burning with golden fire. Dark, atmospheric artwork with incredible detail. A powerful tribute to the ninja who never gave up. Archival-quality print.",
    price: randomPrice(),
    discountPrice: discountTier("Naruto Sage Mode Eyes"),
    image: "/images/poster-anime-8.jpeg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Gojo Satoru Infinity Blue",
    description: "Gojo Satoru's infinite void unleashed in stunning blue neon. The strongest sorcerer's piercing eyes glow with otherworldly power in this dark, atmospheric poster. Jujutsu Kaisen at its finest. Premium heavyweight print.",
    price: randomPrice(),
    discountPrice: discountTier("Gojo Satoru Infinity Blue"),
    image: "/images/poster-anime-9.jpeg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
  {
    name: "Ghost Operator Negative",
    description: "Call of Duty's iconic Ghost operator in a striking red and white tactical poster. Skull mask, tactical headset, and military precision captured in bold graphic design. A must-have for FPS gaming fans. Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Ghost Operator Negative"),
    image: "/images/poster-others-12.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Neon Superbike Red Trail",
    description: "A futuristic superbike blazing through the night with glowing red light trails. Sleek black design meets cyberpunk aesthetics in this high-octane poster. For speed lovers and sci-fi fans alike. Premium satin finish.",
    price: randomPrice(),
    discountPrice: discountTier("Neon Superbike Red Trail"),
    image: "/images/poster-others-13.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Bumblebee Transformers",
    description: "The beloved Autobot Bumblebee in an explosive golden poster. Fist clenched, ready for battle with sparks flying. Bold BEE typography and dramatic lighting. A tribute to Transformers fans everywhere. Gallery-grade print.",
    price: randomPrice(),
    discountPrice: discountTier("Bumblebee Transformers"),
    image: "/images/poster-others-14.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
  {
    name: "Porsche 911 GT3 R RennSport",
    description: "The legendary Porsche 911 GT3 R RennSport in its iconic Martini racing livery. 620 HP of pure racing DNA with heritage-inspired retro spoiler. Bold red typography and studio-quality photography. Premium matte paper.",
    price: randomPrice(),
    discountPrice: discountTier("Porsche 911 GT3 R RennSport"),
    image: "/images/poster-cars-9.jpeg",
    category: "Cars",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
  {
    name: "Tom Cat Winter Streets",
    description: "Everyone's favorite cartoon cat reimagined in stunning 3D animation. Tom in a hoodie on snowy Japanese streets with glowing lanterns. Whimsical, moody, and absolutely charming. Premium heavyweight art paper.",
    price: randomPrice(),
    discountPrice: discountTier("Tom Cat Winter Streets"),
    image: "/images/poster-others-15.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Lightning McQueen & Mater Snow Race",
    description: "Lightning McQueen and Tow Mater racing through snowy mountain passes in this charming Pixar Cars poster. Number 95 and his best buddy in a winter adventure. Vibrant colors on premium satin paper.",
    price: randomPrice(),
    discountPrice: discountTier("Lightning McQueen & Mater Snow Race"),
    image: "/images/poster-others-16.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "F1 Fire & Ice",
    description: "A Formula 1 car engulfed in fire and ice — raw power meets elemental forces in this jaw-dropping poster. Orange flames and blue ice crystals create a surreal motorsport masterpiece. Museum-quality archival print.",
    price: randomPrice(),
    discountPrice: discountTier("F1 Fire & Ice"),
    image: "/images/poster-cars-10.jpeg",
    category: "Cars",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Mercedes AMG GT Ink Splash",
    description: "The Mercedes AMG GT captured in a dramatic black and white ink splash art style. Raw power meets abstract expressionism with red accents. A unique automotive art piece for car lovers. Premium heavyweight paper.",
    price: randomPrice(),
    discountPrice: discountTier("Mercedes AMG GT Ink Splash"),
    image: "/images/poster-cars-11.jpeg",
    category: "Cars",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "BMW M4 GT3 Racing Art",
    description: "The BMW M4 GT3 in its iconic M-stripe livery captured in dynamic racing art style. Bold brush strokes and vibrant colors bring this racing machine to life. THE STGG edition. Premium satin finish.",
    price: randomPrice(),
    discountPrice: discountTier("BMW M4 GT3 Racing Art"),
    image: "/images/poster-cars-12.jpeg",
    category: "Cars",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "BMW M Motorsport Front",
    description: "The BMW M Motorsport machine in a powerful front-facing studio shot. M-stripe livery, aggressive aero kit, and the iconic kidney grille illuminated in dramatic red lighting. Pure German engineering. Premium matte print.",
    price: randomPrice(),
    discountPrice: discountTier("BMW M Motorsport Front"),
    image: "/images/poster-cars-13.jpeg",
    category: "Cars",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Virat Kohli World Cup Champion",
    description: "King Kohli with the ICC World Cup trophy in this electrifying red, white and blue collage. From match-winning centuries to lifting the ultimate prize — the greatest run-chaser in cricket history. Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Virat Kohli World Cup Champion"),
    image: "/images/poster-cricket-3.jpeg",
    category: "Cricket",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
  {
    name: "Lightning McQueen Racing 95",
    description: "Ka-chow! Lightning McQueen tearing up the track in this dynamic racing poster. Number 95 in all his glossy red glory with motion blur and dramatic angles. A Pixar Cars fan essential. Vivid, fade-resistant inks.",
    price: randomPrice(),
    discountPrice: discountTier("Lightning McQueen Racing 95"),
    image: "/images/poster-others-17.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Lightning McQueen Sunset Glory",
    description: "Lightning McQueen cruising into the sunset with dramatic cloud formations. Number 95's iconic bolt design gleaming in warm golden light. A beautiful tribute to the world of Pixar Cars. Premium satin paper.",
    price: randomPrice(),
    discountPrice: discountTier("Lightning McQueen Sunset Glory"),
    image: "/images/poster-others-18.jpeg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Optimus Prime - Transformers",
    description: "The legendary leader of the Autobots in a stunning cinematic close-up. Optimus Prime's intricate mechanical detail and glowing blue eyes captured in a dark, atmospheric palette. A masterpiece for every Transformers fan. Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Optimus Prime - Transformers"),
    image: "/images/download_3.jpg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
  {
    name: "Spider-Man Glitch Art",
    description: "A futuristic take on the web-slinger with vibrant pink and teal glitch effects. This modern digital art style brings a unique energy to the iconic Spider-Man. Perfect for contemporary spaces and Marvel fans. Premium satin finish.",
    price: randomPrice(),
    discountPrice: discountTier("Spider-Man Glitch Art"),
    image: "/images/download_4.jpg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Goku Focus Ultra Instinct",
    description: "Goku in his most powerful state, focused and ready for battle. Dramatic lighting highlights every muscle in this high-contrast monochrome masterpiece. A symbol of pure determination. Gallery-grade archival print.",
    price: randomPrice(),
    discountPrice: discountTier("Goku Focus Ultra Instinct"),
    image: "/images/download_5.jpg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
  {
    name: "Judy Hopps Zootopia",
    description: "Officer Judy Hopps peeking out with her signature determined look. Stunning 3D animation detail makes the fur and eyes look incredibly lifelike. A charming addition to any room. Printed on heavyweight fine art paper.",
    price: randomPrice(),
    discountPrice: discountTier("Judy Hopps Zootopia"),
    image: "/images/download_6.jpg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Tom & Jerry Newspaper",
    description: "The classic duo in a creative 3D render, bursting through a vintage newspaper. Tom's mischievous grin and Jerry's playful escape captured in high-fidelity animation style. Nostalgic yet modern. Premium matte finish.",
    price: randomPrice(),
    discountPrice: discountTier("Tom & Jerry Newspaper"),
    image: "/images/download_7.jpg",
    category: "Others",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Doraemon & Friends Spring",
    description: "A heartwarming scene of Doraemon, Nobita, Shizuka, Gian, and Suneo enjoying a sunny day under cherry blossoms. Vibrant colors and a joyful atmosphere bring this childhood classic to life. Premium satin print.",
    price: randomPrice(),
    discountPrice: discountTier("Doraemon & Friends Spring"),
    image: "/images/download_8.jpg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: false,
  },
  {
    name: "Spider-Man: Until You Win",
    description: "Miles Morales in a gritty, urban-style poster with motivational typography: 'They won't care until you win.' A powerful cinematic shot from above the city streets. Bold, inspirational, and visually striking. Premium matte paper.",
    price: randomPrice(),
    discountPrice: discountTier("Spider-Man: Until You Win"),
    image: "/images/until_you_win.jpg",
    category: "Anime",
    orientation: "portrait",
    isNew: true,
    featured: true,
  },
];

export async function seedDatabase() {
  const existing = await db.select().from(products);
  const hasNewField = existing.length > 0 && existing[0].isNew != null;
  const hasEnoughProducts = existing.length >= 51;
  if (existing.length === 0 || !hasNewField || !hasEnoughProducts) {
    if (existing.length > 0) {
      await db.delete(products);
    }
    await db.insert(products).values(seedProducts);
    console.log("Database seeded with", seedProducts.length, "products");
  }
}
